#!/bin/bash
set -e

source $LOCAL_ERC20_HOME/tests/utils.sh


function get_last_sequncer_generated_certificate () {
    local last_certificate=`docker compose logs topos-sequencer | grep -e 'Submitting new certificate to the TCE network: ' | awk -F': ' '{print $3}' | tail -1` > /dev/null
    echo $last_certificate
}

function check_certificate_delivered () {
    docker compose logs $1 | grep -e "Certificate delivered $2" > /dev/null
    local certificate_delivered=$?
    echo $certificate_delivered
}


network_started=0

# Start network if it is not running
is_running=$(is_network_running)
if [ $is_running -eq 1 ]; then
    echo "Test network is not running, starting it now..."
    start_network
    network_started=1
    sleep 5 # Warm up network
fi


# Perform test
echo "Executing test to check if certificates are broadcasted..."
# Get last certificate generated by topos sequencer
test_certificate=$(get_last_sequncer_generated_certificate topos-sequencer)
echo "Topos certificate: $test_certificate"

# Get TCE endpoints
TCE_NODES=$(docker compose config --services | grep -e topos-node)
TCE_NODES_NUMBER=$(echo $TCE_NODES | wc -w)

for i in {1..10};
do
    counter=0
    for node in $TCE_NODES
    do
        echo "Checking if certificate $test_certificate is delivered to $node"
        delivered=$(check_certificate_delivered $node $test_certificate)
        if [ $delivered -eq 0 ]; then
            echo "Certificate $test_certificate delivered to $node"
            counter=$((counter+1))
        else
            echo "Certificate $test_certificate IS NOT delivered to $node"
        fi
    done
    if [ $counter -eq $TCE_NODES_NUMBER ]; then
        echo "Certificate $test_certificate delivered to all TCE nodes"
        break
    else
        echo "Certificate $test_certificate IS NOT delivered to all TCE nodes"
        if [[ "$i" != '10' ]]; then
            echo "Trying again in 5 seconds for $(($i+1)) time"
            sleep 5
            continue
        fi
        if [ $network_started -eq 1 ]; then
            echo "Test failed, shutting down network started for this test"
            stop_network
        fi        
        exit 1
    fi

done



# Stop network if started for this test
if [ $network_started -eq 1 ]; then
    echo "Shutting down network started for this test"
    stop_network
fi
